### ISSUE TITLE
Scrollbar customization cause performance issues

### ISSUE THREAD

**Issue by glebcha** [KevinVandy/material-react-table#890]
### material-react-table version

v2.1.0

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

You can easily reproduce it by adding customization for webkit scrollbars in [storybook example](https://www.material-react-table.dev/?path=/story/features-virtualization--max-virtualization).

### Minimal, Reproducible Example - (Optional, but Recommended)

```css
div[class^="MuiTableContainer-root"] {
  --scrollbar-background: #bbe0fa;
  --scrollbar-hover-background: #a5d7fa;

  &::-webkit-scrollbar {
    width: .5em;
    height: .5em;
  }

  &::-webkit-scrollbar-button {
    background: var(--scrollbar-background);
  }

  &::-webkit-scrollbar-thumb {
    background: var(--scrollbar-background);
    border-radius: 6px;
  }

  &::-webkit-scrollbar-thumb:hover {
    background: var(--scrollbar-hover-background);
  }
}
```

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/2785780/f4c28bad-abd0-440e-a73a-be03c866be1f

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
